# Generated by Django 3.2 on 2022-08-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
