# Generated by Django 3.2 on 2022-08-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220830_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
