# Generated by Django 3.2 on 2022-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='paper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
