# Generated by Django 3.2 on 2022-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
